#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          activemq
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop activemq for stomp services.
### END INIT INFO

/usr/local/apache-activemq/bin/activemq "$@"
